### ISSUE TITLE
PDF the wrong format for web based document delivery.

### ISSUE THREAD

**Issue by dwkns** [GovernmentCommunicationsHeadquarters/BoilingFrogs#3]
PDF is a dreadful format for delivering information on screen. They are good for one thing and one thing only, printing. 

https://www.nngroup.com/articles/pdf-unfit-for-human-consumption/

And I suspect that considering you are decimianting this document via github your audience is likely to be the type of people who read things on screen, rather than print them out for the train ride home. 

This is both a communication failure and a user experience failure. And you claim that...
"...GCHQ has a reputation for the best technical delivery organisation in the UK Government, itself a leading example of digital Gov around the world".

**Comment by FredericJacobs** [comment]
There are a few things I'ld like to note on that issue too:
- Apparently the UK Government has no open formats policy since the original file appears to be a binary binary docx file from Word 2016 and then exported to PDF. 

```
ExifTool Version Number : 10.11
File Name: GCHQ_Boiling_Frogs.pdf
File Size: 1901 kB
File Type: PDF
File Type Extension: pdf
MIME Type: application/pdf
PDF Version: 1.5
Linearized: No
Page Count: 60
Language: en-GB
Tagged PDF: Yes
Producer: Microsoft® Word 2016
Creator:  Microsoft® Word 2016
Create Date:  2016:05:12 14:21:49+01:00
Modify Date:  2016:05:12 14:21:49+01:00
```
- Dropping documents on GitHub has very limited usefulness if they are not in an open format that supports line by line changes for version control.
- GCHQ uses [PDF exploits](https://s3.amazonaws.com/s3.documentcloud.org/documents/1505161/gchq-iphone.pdf) against Intelligence targets. The format is known as being really hard to parse without memory corruption. Quite ironic to distribute boiling frogs under that format.

I would love to see a Markdown (Pandoc) or LaTeX version of the paper be released in this repository.

One last thing, [Git LFS](https://git-lfs.github.com/) is the right place to store .jpeg & .pdf files, not in your Git tree. All these things suggest that there is still some work to do on software development and organisational change ;)

**Comment by alper** [comment]
There was a cleaned up web version of this by GDS wasn't there?

**Update:** It wasn't GDS but COOPDigital and they cleaned up the PDF but didn't convert it to web here: https://digital.blogs.coop/2016/06/21/making-design-better-by-being-open/

**Comment by russ-b-ukg** [comment]
We agree that PDF isn't best for screen, but much of our core audience for Boiling Frogs is the "download and print" folks - thanks
